language: node_js
node_js:
  - 12
services:
  - docker
script:
  - docker build -t pablobfonseca/node .
  - docker images pablobfonseca/node
before_deploy:
  - echo "$HUB_PASSWORD" | docker login -u "$HUB_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push pablobfonseca/node
  on:
    branch: master
